In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("modal_experiment_v1_stimulus_candidates_v6.csv")
df.head()

,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,order_pair_id,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
1,Training,T1,Museum entrance,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
2,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
3,Training,T2,Library rooms,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
4,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

### context-only norming

In [3]:
cols = [
    "phase",
    "item_id",
    "domain",
    "D_status",
    "E_status",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "context_only_deontic_question",
    "context_only_epistemic_question",
]
context_only = df[cols]

context_only.head()

,phase,item_id,domain,D_status,E_status,temporal_orientation,order_1,order_2,context_order_1,context_order_2,context_only_deontic_question,context_only_epistemic_question
0,Training,T1,Museum entrance,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Lina is visiting a history museum tomorrow for...,Lina has a green visitor badge that is valid a...,According to the rules or permissions describe...,Based on the information described in the stor...
1,Training,T1,Museum entrance,D unspecified,E+ (explicit uncertainty / live alternatives),past perfect / present progressive or stative,N-E,E-N,Lina visited a history museum this morning for...,Lina's classmate knows she entered through eit...,According to the rules or permissions describe...,Based on the information described in the stor...
2,Training,T2,Library rooms,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Priya is doing research at the library tomorro...,Priya's researcher card lists both the reading...,According to the rules or permissions describe...,Based on the information described in the stor...
3,Training,T2,Library rooms,D unspecified,E+ (explicit uncertainty / live alternatives),past perfect / present progressive or stative,N-E,E-N,Priya is doing research at the library right n...,Priya's classmate knows she is in either the r...,According to the rules or permissions describe...,Based on the information described in the stor...
4,Training,T3,Community center,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Nora is going to the community center this aft...,Nora's membership includes both the swimming p...,According to the rules or permissions describe...,Based on the information described in the stor...

In [4]:
context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
    lambda x: x.replace("rules or permissions", "<b>rules or permissions</b>")
)
context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(
    lambda x: x.replace("information", "<b>information</b>")
)

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_9685/3176482508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_9685/3176482508.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(

In [5]:
context_only = pd.concat([
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                }),
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                })
    ])

context_only["D_status"] = context_only["D_status"].map({"D+": 1, "D unspecified": 0, "D-": -1})
context_only["E_status"] = context_only["E_status"].map({"E+ (explicit uncertainty / live alternatives)": 1, "E+ (open / not ruled out)": 0, "E-": -1})

co_d = context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_deontic_question",
            ]].rename(columns={
                "D_status":"modal_possibility",
                "context_only_deontic_question":"context_only_question"
                })
co_d["judgement_flavour"] = "Deontic"
co_d["context_only_option_3"] = "The story does not say"

co_e = context_only[[
            "phase",
            "item_id",
            "domain",
            "E_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_epistemic_question",
            ]].rename(columns={
                "E_status":"modal_possibility",
                "context_only_epistemic_question":"context_only_question"
                })
co_e["judgement_flavour"] = "Epistemic"
co_e["context_only_option_3"] = ""


context_only = pd.concat([co_d, co_e]).sort_values(by=["item_id", "judgement_flavour", "modal_possibility", "order"]).reset_index(drop=True)

context_only.head()

,phase,item_id,domain,modal_possibility,temporal_orientation,order,context_order,context_only_question,judgement_flavour,context_only_option_3
0,Critical Test,C1,Zoo animal-care room,-1.0,past perfect,E-D-N,Aisha's classmates lost track of her after lun...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
1,Critical Test,C1,Zoo animal-care room,-1.0,past perfect,N-E-D,Aisha is photographing exhibits at the zoo for...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
2,Critical Test,C1,Zoo animal-care room,1.0,future eventive,D-N-E,Aisha's volunteer credential permits her to wo...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
3,Critical Test,C1,Zoo animal-care room,1.0,future eventive,N-D-E,Aisha is volunteering at the zoo tomorrow as p...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
4,Critical Test,C1,Zoo animal-care room,-1.0,future eventive,D-N-E,Aisha's volunteer credential permits her to wo...,Based on the <b>information</b> described in t...,Epistemic,

In [6]:
context_only["group"] = (context_only.index + context_only.index // 8) % 8 + 1
context_only["group"].tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7]

In [7]:
print(context_only.shape)

context_only.to_csv("context_only_stimulus.csv")

(192, 11)

### whole-scenario norming

In [8]:
df = pd.read_csv("modal_experiment_v1_stimulus_candidates_v6.csv")
df.head()

,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,order_pair_id,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
1,Training,T1,Museum entrance,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
2,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
3,Training,T2,Library rooms,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
4,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

In [9]:
cols = [
    "phase",
    "item_id",
    "domain",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "whole_scenario_may_target", "whole_scenario_possible_target",
    "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
    "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation"
]

whole_scenario = df[cols]

whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(
    lambda x: "Which interpretation better matches what the speaker is talking about?" if x[-1] == "." \
        else "Which interpretation better matches what the speaker is asking about?"
)

whole_scenario.head()

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_9685/1404377874.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(

,phase,item_id,domain,temporal_orientation,order_1,order_2,context_order_1,context_order_2,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,whole_scenario_question
0,Training,T1,Museum entrance,future eventive,N-D,D-N,Lina is visiting a history museum tomorrow for...,Lina has a green visitor badge that is valid a...,Lina may use the side entrance tomorrow.,It is possible for Lina to use the side entran...,Definitely about whether Lina is permitted to ...,Definitely about whether Lina will use the sid...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Which interpretation better matches what the s...
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,E-N,Lina visited a history museum this morning for...,Lina's classmate knows she entered through eit...,Lina may have used the side entrance.,It is possible for Lina to have used the side ...,Definitely about whether Lina was permitted to...,Definitely about whether Lina used the side en...,Expected non-deontic interpretation,Expected epistemic interpretation,Which interpretation better matches what the s...
2,Training,T2,Library rooms,future eventive,N-D,D-N,Priya is doing research at the library tomorro...,Priya's researcher card lists both the reading...,Which room may Priya work in tomorrow?,Which room is it possible for Priya to work in...,Definitely about which room Priya is permitted...,Definitely about which room Priya will work in...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Which interpretation better matches what the s...
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,E-N,Priya is doing research at the library right n...,Priya's classmate knows she is in either the r...,Which room may Priya be working in now?,Which room is it possible for Priya to be work...,Definitely about which room Priya is permitted...,Definitely about which room Priya is working i...,Expected non-deontic interpretation,Expected epistemic interpretation,Which interpretation better matches what the s...
4,Training,T3,Community center,future eventive,N-D,D-N,Nora is going to the community center this aft...,Nora's membership includes both the swimming p...,Nora may use the pool this afternoon.,It is possible for Nora to use the pool this a...,Definitely about whether Nora is permitted to ...,Definitely about whether Nora will use the poo...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Which interpretation better matches what the s...

In [10]:
whole_scenario = pd.concat([
        whole_scenario[[
            "phase",
            "item_id",
            "domain",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "whole_scenario_may_target", "whole_scenario_possible_target",
            "whole_scenario_question",
            "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
            "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation"
            ]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                }),
        whole_scenario[[
            "phase",
            "item_id",
            "domain",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "whole_scenario_may_target", "whole_scenario_possible_target",
            "whole_scenario_question",
            "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
            "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation"
            ]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                }),
    ])


whole_scenario["whole_scenario_deontic_reading"] = whole_scenario["whole_scenario_deontic_reading"].apply(
    lambda x: x.replace(", according to the rules or permissions", "<br>(according to the rules or permissions)"
    ).replace("Definitely about w", "W")
)

whole_scenario["whole_scenario_epistemic_reading"] = whole_scenario["whole_scenario_epistemic_reading"].apply(
    lambda x: x.replace(", based on the available information", "<br>(based on the available information)"
    ).replace("Definitely about w", "W")
)

whole_scenario.head()

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,It is possible for Lina to use the side entran...,Which interpretation better matches what the s...,Whether Lina is permitted to use the side entr...,Whether Lina will use the side entrance tomorr...,Expected root/deontic interpretation,Expected non-epistemic interpretation
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,It is possible for Lina to have used the side ...,Which interpretation better matches what the s...,Whether Lina was permitted to use the side ent...,Whether Lina used the side entrance<br>(based ...,Expected non-deontic interpretation,Expected epistemic interpretation
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which room is it possible for Priya to work in...,Which interpretation better matches what the s...,Which room Priya is permitted to work in tomor...,Which room Priya will work in tomorrow<br>(bas...,Expected root/deontic interpretation,Expected non-epistemic interpretation
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which room is it possible for Priya to be work...,Which interpretation better matches what the s...,Which room Priya is permitted to work in now<b...,Which room Priya is working in now<br>(based o...,Expected non-deontic interpretation,Expected epistemic interpretation
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,It is possible for Nora to use the pool this a...,Which interpretation better matches what the s...,Whether Nora is permitted to use the pool this...,Whether Nora will use the pool this afternoon<...,Expected root/deontic interpretation,Expected non-epistemic interpretation

In [11]:
whole_scenario_may = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "whole_scenario_may_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation"
        ]].rename(columns={
            "whole_scenario_may_target":"whole_scenario_response",
        })
whole_scenario_may["reponse_type"] = "may"

whole_scenario_possible = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "whole_scenario_possible_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation"
        ]].rename(columns={
            "whole_scenario_possible_target":"whole_scenario_response",
        })
whole_scenario_may["reponse_type"] = "possible"


whole_scenario_may.head()

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,reponse_type
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,Which interpretation better matches what the s...,Whether Lina is permitted to use the side entr...,Whether Lina will use the side entrance tomorr...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,Which interpretation better matches what the s...,Whether Lina was permitted to use the side ent...,Whether Lina used the side entrance<br>(based ...,Expected non-deontic interpretation,Expected epistemic interpretation,possible
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which interpretation better matches what the s...,Which room Priya is permitted to work in tomor...,Which room Priya will work in tomorrow<br>(bas...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which interpretation better matches what the s...,Which room Priya is permitted to work in now<b...,Which room Priya is working in now<br>(based o...,Expected non-deontic interpretation,Expected epistemic interpretation,possible
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,Which interpretation better matches what the s...,Whether Nora is permitted to use the pool this...,Whether Nora will use the pool this afternoon<...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible

In [12]:
# participants see either may or possible, not both. 

whole_scenario_may["group"] = (whole_scenario_may.index + whole_scenario_may.index // 2) % 2 + 1
print(whole_scenario_may["group"].tolist())

whole_scenario_possible["group"] = (whole_scenario_possible.index + whole_scenario_possible.index // 2) % 2 + 3
print(whole_scenario_possible["group"].tolist())

[1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1]
[3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3]

In [ ]:
whole_scenario = pd.concat([whole_scenario_may, whole_scenario_possible])

# whole_scenario.to_csv("whole_scenario_stimulus.csv")
print(whole_scenario.shape)
whole_scenario.head()

(192, 14)

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,reponse_type,group
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,Which interpretation better matches what the s...,Whether Lina is permitted to use the side entr...,Whether Lina will use the side entrance tomorr...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible,1
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,Which interpretation better matches what the s...,Whether Lina was permitted to use the side ent...,Whether Lina used the side entrance<br>(based ...,Expected non-deontic interpretation,Expected epistemic interpretation,possible,2
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which interpretation better matches what the s...,Which room Priya is permitted to work in tomor...,Which room Priya will work in tomorrow<br>(bas...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible,2
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which interpretation better matches what the s...,Which room Priya is permitted to work in now<b...,Which room Priya is working in now<br>(based o...,Expected non-deontic interpretation,Expected epistemic interpretation,possible,1
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,Which interpretation better matches what the s...,Whether Nora is permitted to use the pool this...,Whether Nora will use the pool this afternoon<...,Expected root/deontic interpretation,Expected non-epistemic interpretation,possible,1

In [16]:
# make it so that which interpretation is on the left/right depends on the group of the person.

whole_scenario_de = whole_scenario.copy()
whole_scenario_de["left_interpretation"] = whole_scenario_de["whole_scenario_deontic_reading"]
whole_scenario_de["right_interpretation"] = whole_scenario_de["whole_scenario_epistemic_reading"]
whole_scenario_de["scale_order"] = "deontic-epistemic"

whole_scenario_ed = whole_scenario.copy()
whole_scenario_ed["left_interpretation"] = whole_scenario_ed["whole_scenario_epistemic_reading"]
whole_scenario_ed["right_interpretation"] = whole_scenario_ed["whole_scenario_deontic_reading"]
whole_scenario_ed["scale_order"] = "epistemic-deontic"
whole_scenario_ed["group"] = whole_scenario_ed["group"] + 4
print(whole_scenario_ed["group"].tolist())

whole_scenario_combined = pd.concat([whole_scenario_de, whole_scenario_ed])
whole_scenario_combined.to_csv("whole_scenario_stimulus.csv")

[5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7]