In [17]:
import pandas as pd

In [18]:
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,DAX is the functional auxiliary nonce form and MIP is the lexical-adjective nonce form in this draft. Counterbalance nonce forms across morphosyntactic conditions in the final experiment. Context components that can appear first in an order variant introduce the participant by name rather than with an ungrounded pronoun; pronouns are retained later where their antecedent is clear.,,,,
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,Context-only and whole-scenario norming must use the same context wording/order for a given item version. Whole-scenario norming differs only by appending the familiar-English target sentence.,,,,
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,"For test/filler items, three order-pair types are balanced exactly: P1=N-E-D + E-D-N; P2=D-N-E + N-D-E; P3=E-N-D + D-E-N. Each pair occurs 8 times, and each of the six individual three-part orders therefore occurs 8 times.",,,,
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,"For training items, each root/deontic candidate has N-D and D-N versions; each epistemic candidate has N-E and E-N versions. The untrained flavor is not made false during training.",,,,
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,"Training candidate syntax is balanced 4/4/4 per flavor across Declarative, Wh-question, and Yes/no inversion. Critical test and filler targets remain declarative to keep the flavor-transfer judgment syntactically conservative. Norming practice/example trials should be declarative.",,,,
# GENERAL NOTE,,,,,,,,,,,,,,,,,,,,,,,,,,,,E_status records whether the target proposition is epistemically possible (E+) or ruled out (E-). epistemic_support_type separately records HOW E+ is established: explicit live alternatives/positive evidence versus merely remaining open because nothing rules it out. Both receive 'Yes' to the context-only epistemic possibility question because both are compatible with the information state.,,,,

df = pd.read_csv("modal_experiment_v1_stimulus_candidates_v8.csv")
df.head()

,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,order_pair_id,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
1,Training,T1,Museum entrance,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
2,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
3,Training,T2,Library rooms,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
4,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

### context-only norming

In [19]:
cols = [
    "phase",
    "item_id",
    "domain",
    "D_status",
    "E_status",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "context_only_deontic_question",
    "context_only_epistemic_question",
]
context_only = df[cols]

context_only.head()

,phase,item_id,domain,D_status,E_status,temporal_orientation,order_1,order_2,context_order_1,context_order_2,context_only_deontic_question,context_only_epistemic_question
0,Training,T1,Museum entrance,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Lina is visiting a history museum tomorrow for...,Lina has a green visitor badge that is valid a...,According to the rules or permissions describe...,Based on the information described in the stor...
1,Training,T1,Museum entrance,D unspecified,E+ (explicit uncertainty / live alternatives),past perfect / present progressive or stative,N-E,E-N,Lina visited a history museum this morning for...,Lina's classmate knows she entered through eit...,According to the rules or permissions describe...,Based on the information described in the stor...
2,Training,T2,Library rooms,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Priya is doing research at the library tomorro...,Priya's researcher card lists both the reading...,According to the rules or permissions describe...,Based on the information described in the stor...
3,Training,T2,Library rooms,D unspecified,E+ (explicit uncertainty / live alternatives),past perfect / present progressive or stative,N-E,E-N,Priya is doing research at the library right n...,Priya's classmate knows she is in either the r...,According to the rules or permissions describe...,Based on the information described in the stor...
4,Training,T3,Community center,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Nora is going to the community center this aft...,Nora's membership includes both the swimming p...,According to the rules or permissions describe...,Based on the information described in the stor...

In [20]:
context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
    lambda x: x.replace("rules or permissions", "<b>rules or permissions</b>")
)
context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(
    lambda x: x.replace("information", "<b>information</b>")
)

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_29726/3176482508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_29726/3176482508.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(

In [21]:
context_only = pd.concat([
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                }),
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                })
    ])

context_only["D_status"] = context_only["D_status"].map({"D+": 1, "D unspecified": 0, "D-": -1})
context_only["E_status"] = context_only["E_status"].map({"E+ (explicit uncertainty / live alternatives)": 1, "E+ (open / not ruled out)": 0, "E-": -1})

co_d = context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_deontic_question",
            ]].rename(columns={
                "D_status":"modal_possibility",
                "context_only_deontic_question":"context_only_question"
                })
co_d["judgement_flavour"] = "Deontic"
co_d["context_only_option_3"] = "The story does not say"

co_e = context_only[[
            "phase",
            "item_id",
            "domain",
            "E_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_epistemic_question",
            ]].rename(columns={
                "E_status":"modal_possibility",
                "context_only_epistemic_question":"context_only_question"
                })
co_e["judgement_flavour"] = "Epistemic"
co_e["context_only_option_3"] = ""


context_only = pd.concat([co_d, co_e]).sort_values(by=["item_id", "judgement_flavour", "modal_possibility", "order"]).reset_index(drop=True)

context_only.head()

,phase,item_id,domain,modal_possibility,temporal_orientation,order,context_order,context_only_question,judgement_flavour,context_only_option_3
0,Critical Test,C1,Zoo animal-care room,-1.0,past perfect,E-D-N,Aisha's classmates lost track of her after lun...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
1,Critical Test,C1,Zoo animal-care room,-1.0,past perfect,N-E-D,Aisha is photographing exhibits at the zoo for...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
2,Critical Test,C1,Zoo animal-care room,1.0,future eventive,D-N-E,Aisha's volunteer credential permits her to wo...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
3,Critical Test,C1,Zoo animal-care room,1.0,future eventive,N-D-E,Aisha is volunteering at the zoo tomorrow as p...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
4,Critical Test,C1,Zoo animal-care room,-1.0,future eventive,D-N-E,Aisha's volunteer credential permits her to wo...,Based on the <b>information</b> described in t...,Epistemic,

In [22]:
context_only["group"] = (context_only.index + context_only.index // 8) % 8 + 1
context_only["group"].tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7]

In [23]:
print(context_only.shape)

context_only.to_csv("context_only_stimulus.csv")

(192, 11)

### whole-scenario norming

In [24]:
df = pd.read_csv("modal_experiment_v1_stimulus_candidates_v8.csv")
df.head()

,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,order_pair_id,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
1,Training,T1,Museum entrance,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
2,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
3,Training,T2,Library rooms,NaN,D unspecified,E+ (explicit uncertainty / live alternatives),no relevant permission rule stated,the story explicitly presents the target as on...,past perfect / present progressive or stative,TE,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
4,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information,no explicit epistemic evidence; the target eve...,future eventive,TR,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

In [25]:
cols = [
    "phase",
    "item_id",
    "domain",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "whole_scenario_may_target", "whole_scenario_possible_target",
    "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
    "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
    "syntax"
]

whole_scenario = df[cols]

whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(
    lambda x: "Which interpretation better matches what the speaker is talking about?" if x[-1] == "." \
        else "Which interpretation better matches what the speaker is asking about?"
)

whole_scenario.head()

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_29726/743179959.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(

,phase,item_id,domain,temporal_orientation,order_1,order_2,context_order_1,context_order_2,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,whole_scenario_question
0,Training,T1,Museum entrance,future eventive,N-D,D-N,Lina is visiting a history museum tomorrow for...,Lina has a green visitor badge that is valid a...,Lina may use the side entrance tomorrow.,It is possible for Lina to use the side entran...,About whether Lina using the side entrance tom...,About whether Lina using the side entrance tom...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,Which interpretation better matches what the s...
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,E-N,Lina visited a history museum this morning for...,Lina's classmate knows she entered through eit...,Lina may have used the side entrance.,It is possible for Lina to have used the side ...,About whether Lina using the side entrance ear...,About whether Lina using the side entrance ear...,Expected non-deontic interpretation,Expected epistemic interpretation,Declarative,Which interpretation better matches what the s...
2,Training,T2,Library rooms,future eventive,N-D,D-N,Priya is doing research at the library tomorro...,Priya's researcher card lists both the reading...,Which room may Priya work in tomorrow?,Which room is it possible for Priya to work in...,About which room her working in tomorrow is al...,About which room her working in tomorrow is co...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Wh-question,Which interpretation better matches what the s...
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,E-N,Priya is doing research at the library right n...,Priya's classmate knows she is in either the r...,Which room may Priya be working in now?,Which room is it possible for Priya to be work...,About which room her working in now is allowed...,About which room her working in now is consist...,Expected non-deontic interpretation,Expected epistemic interpretation,Wh-question,Which interpretation better matches what the s...
4,Training,T3,Community center,future eventive,N-D,D-N,Nora is going to the community center this aft...,Nora's membership includes both the swimming p...,Nora may use the pool this afternoon.,It is possible for Nora to use the pool this a...,About whether Nora using the pool this afterno...,About whether Nora using the pool this afterno...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,Which interpretation better matches what the s...

In [26]:
whole_scenario = pd.concat([
        whole_scenario[[
            "phase",
            "item_id",
            "domain",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "whole_scenario_may_target", "whole_scenario_possible_target",
            "whole_scenario_question",
            "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
            "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
            "syntax"
            ]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                }),
        whole_scenario[[
            "phase",
            "item_id",
            "domain",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "whole_scenario_may_target", "whole_scenario_possible_target",
            "whole_scenario_question",
            "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
            "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
            "syntax"
            ]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                }),
    ])


whole_scenario.head()

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,It is possible for Lina to use the side entran...,Which interpretation better matches what the s...,About whether Lina using the side entrance tom...,About whether Lina using the side entrance tom...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,It is possible for Lina to have used the side ...,Which interpretation better matches what the s...,About whether Lina using the side entrance ear...,About whether Lina using the side entrance ear...,Expected non-deontic interpretation,Expected epistemic interpretation,Declarative
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which room is it possible for Priya to work in...,Which interpretation better matches what the s...,About which room her working in tomorrow is al...,About which room her working in tomorrow is co...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Wh-question
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which room is it possible for Priya to be work...,Which interpretation better matches what the s...,About which room her working in now is allowed...,About which room her working in now is consist...,Expected non-deontic interpretation,Expected epistemic interpretation,Wh-question
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,It is possible for Nora to use the pool this a...,Which interpretation better matches what the s...,About whether Nora using the pool this afterno...,About whether Nora using the pool this afterno...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative

In [27]:
whole_scenario_may = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "whole_scenario_may_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
        "syntax"
        ]].rename(columns={
            "whole_scenario_may_target":"whole_scenario_response",
        })
whole_scenario_may["response_type"] = "may"

whole_scenario_possible = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "whole_scenario_possible_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
        "syntax"
        ]].rename(columns={
            "whole_scenario_possible_target":"whole_scenario_response",
        })
whole_scenario_may["response_type"] = "possible"


whole_scenario_may.head()

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,response_type
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,Which interpretation better matches what the s...,About whether Lina using the side entrance tom...,About whether Lina using the side entrance tom...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,possible
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,Which interpretation better matches what the s...,About whether Lina using the side entrance ear...,About whether Lina using the side entrance ear...,Expected non-deontic interpretation,Expected epistemic interpretation,Declarative,possible
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which interpretation better matches what the s...,About which room her working in tomorrow is al...,About which room her working in tomorrow is co...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Wh-question,possible
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which interpretation better matches what the s...,About which room her working in now is allowed...,About which room her working in now is consist...,Expected non-deontic interpretation,Expected epistemic interpretation,Wh-question,possible
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,Which interpretation better matches what the s...,About whether Nora using the pool this afterno...,About whether Nora using the pool this afterno...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,possible

In [28]:
# participants see either may or possible, not both. 

whole_scenario_may["group"] = (whole_scenario_may.index + whole_scenario_may.index // 2) % 2 + 1
print(whole_scenario_may["group"].tolist())

whole_scenario_possible["group"] = (whole_scenario_possible.index + whole_scenario_possible.index // 2) % 2 + 3
print(whole_scenario_possible["group"].tolist())

[1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1]
[3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3]

In [29]:
whole_scenario = pd.concat([whole_scenario_may, whole_scenario_possible])

whole_scenario["whole_scenario_response"] = whole_scenario["whole_scenario_response"].apply(
    lambda x: x.split(" — ")[0])

print(whole_scenario.shape)
whole_scenario.head()

(192, 15)

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,response_type,group
0,Training,T1,Museum entrance,future eventive,N-D,Lina is visiting a history museum tomorrow for...,Lina may use the side entrance tomorrow.,Which interpretation better matches what the s...,About whether Lina using the side entrance tom...,About whether Lina using the side entrance tom...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,possible,1
1,Training,T1,Museum entrance,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,Lina may have used the side entrance.,Which interpretation better matches what the s...,About whether Lina using the side entrance ear...,About whether Lina using the side entrance ear...,Expected non-deontic interpretation,Expected epistemic interpretation,Declarative,possible,2
2,Training,T2,Library rooms,future eventive,N-D,Priya is doing research at the library tomorro...,Which room may Priya work in tomorrow?,Which interpretation better matches what the s...,About which room her working in tomorrow is al...,About which room her working in tomorrow is co...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Wh-question,possible,2
3,Training,T2,Library rooms,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,Which room may Priya be working in now?,Which interpretation better matches what the s...,About which room her working in now is allowed...,About which room her working in now is consist...,Expected non-deontic interpretation,Expected epistemic interpretation,Wh-question,possible,1
4,Training,T3,Community center,future eventive,N-D,Nora is going to the community center this aft...,Nora may use the pool this afternoon.,Which interpretation better matches what the s...,About whether Nora using the pool this afterno...,About whether Nora using the pool this afterno...,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,possible,1

In [30]:
# make it so that which interpretation is on the left/right depends on the group of the person.

whole_scenario_de = whole_scenario.copy()
whole_scenario_de["left_interpretation"] = whole_scenario_de["whole_scenario_deontic_reading"]
whole_scenario_de["right_interpretation"] = whole_scenario_de["whole_scenario_epistemic_reading"]
whole_scenario_de["scale_order"] = "deontic-epistemic"

whole_scenario_ed = whole_scenario.copy()
whole_scenario_ed["left_interpretation"] = whole_scenario_ed["whole_scenario_epistemic_reading"]
whole_scenario_ed["right_interpretation"] = whole_scenario_ed["whole_scenario_deontic_reading"]
whole_scenario_ed["scale_order"] = "epistemic-deontic"
whole_scenario_ed["group"] = whole_scenario_ed["group"] + 4
print(whole_scenario_ed["group"].tolist())

whole_scenario_combined = pd.concat([whole_scenario_de, whole_scenario_ed])

whole_scenario_combined["left_interpretation"] = whole_scenario_combined["left_interpretation"].apply(
    lambda x: x.replace(
        "rules or permissions", "<span style='color:#C62828'>rules or permissions</span>"
        ).replace(
            "available information", "<span style='color:#C62828'>available information</span>"
        )
)

whole_scenario_combined["right_interpretation"] = whole_scenario_combined["right_interpretation"].apply(
    lambda x: x.replace(
        "rules or permissions", "<span style='color:#1565C0'>rules or permissions</span>"
        ).replace(
            "available information", "<span style='color:#1565C0'>available information</span>"
        )
)

whole_scenario_combined.to_csv("whole_scenario_stimulus.csv")

[5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7]

In [31]:
# also update the practice trials to use the same orders

whole_scenario_practice = pd.read_csv("norming_practice_trials_whole_scenario.csv")

practice_groups = []
for group in range(1, 9):
    p = whole_scenario_practice.copy()
    p["group"] = group
    if group > 4:
        p["left_interpretation"] = p["whole_scenario_epistemic_reading"]
        p["right_interpretation"] = p["whole_scenario_deontic_reading"]
        p["expected_preference"] = p["expected_preference"].apply(
            lambda x: '5' if x == '1' else '1' if x == '5' else x
        )
        p["scale_order"] = "epistemic-deontic"
    else:
        p["left_interpretation"] = p["whole_scenario_deontic_reading"]
        p["right_interpretation"] = p["whole_scenario_epistemic_reading"]
        p["scale_order"] = "deontic-epistemic"
    practice_groups.append(p)

whole_scenario_practice_grouped = pd.concat(practice_groups)

whole_scenario_practice_grouped["left_interpretation"] = whole_scenario_practice_grouped["left_interpretation"].apply(
    lambda x: x.replace(
        "rules or permissions", "<span style='color:#C62828'>rules or permissions</span>"
        ).replace(
            "available information", "<span style='color:#C62828'>available information</span>"
        )
)

whole_scenario_practice_grouped["right_interpretation"] = whole_scenario_practice_grouped["right_interpretation"].apply(
    lambda x: x.replace(
        "rules or permissions", "<span style='color:#1565C0'>rules or permissions</span>"
        ).replace(
            "available information", "<span style='color:#1565C0'>available information</span>"
        )
)

whole_scenario_practice_grouped

,practice_id,context,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_preference,group,left_interpretation,right_interpretation,scale_order
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,1,1,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,deontic-epistemic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,5,1,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,deontic-epistemic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,1,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,deontic-epistemic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,1,2,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,deontic-epistemic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,5,2,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,deontic-epistemic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,2,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,deontic-epistemic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,1,3,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,deontic-epistemic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,5,3,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,deontic-epistemic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,3,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,deontic-epistemic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,1,4,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,deontic-epistemic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,5,4,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,deontic-epistemic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,4,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,deontic-epistemic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,5,5,About whether Ava using the greenhouse is cons...,About whether Ava using the greenhouse is allo...,epistemic-deontic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,1,5,About whether Leo going backstage earlier is c...,About whether Leo going backstage earlier was ...,epistemic-deontic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,5,About whether Rosa being at Court 2 now is con...,About whether Rosa being at Court 2 now is all...,epistemic-deontic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,5,6,About whether Ava using the greenhouse is cons...,About whether Ava using the greenhouse is allo...,epistemic-deontic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,1,6,About whether Leo going backstage earlier is c...,About whether Leo going backstage earlier was ...,epistemic-deontic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,6,About whether Rosa being at Court 2 now is con...,About whether Rosa being at Court 2 now is all...,epistemic-deontic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,5,7,About whether Ava using the greenhouse is cons...,About whether Ava using the greenhouse is allo...,epistemic-deontic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,1,7,About whether Leo going backstage earlier is c...,About whether Leo going backstage earlier was ...,epistemic-deontic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,7,About whether Rosa being at Court 2 now is con...,About whether Rosa being at Court 2 now is all...,epistemic-deontic
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,Which interpretation better matches what the s...,About whether Ava using the greenhouse is allo...,About whether Ava using the greenhouse is cons...,5,8,About whether Ava using the greenhouse is cons...,About whether Ava using the greenhouse is allo...,epistemic-deontic
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,Which interpretation better matches what the s...,About whether Leo going backstage earlier was ...,About whether Leo going backstage earlier is c...,1,8,About whether Leo going backstage earlier is c...,About whether Leo going backstage earlier was ...,epistemic-deontic
2,P3,Rosa belongs to a sports club whose rules perm...,Rosa is a beginner tennis player.,Which interpretation better matches what the s...,About whether Rosa being at Court 2 now is all...,About whether Rosa being at Court 2 now is con...,Neither interpretation works here,8,About whether Rosa being at Court 2 now is con...,About whether Rosa being at Court 2 now is all...,epistemic-deontic

In [32]:
whole_scenario_practice_grouped.to_csv("norming_practice_trials_whole_scenario_grouped.csv")