In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../modal_experiment_v1_positive_flavour_stimulus_candidates.csv")
df = df.loc[df["item_id"].notna()].copy()
df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
6,6,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
7,7,Training,T1,Museum entrance,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
8,8,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
9,9,Training,T2,Library rooms,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
10,10,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

### context-only norming

In [3]:
cols = [
    "phase",
    "item_id",
    "domain",
    "D_status",
    "E_status",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "context_only_deontic_question",
    "context_only_epistemic_question",
]
context_only = df[cols]

context_only.head()

,phase,item_id,domain,D_status,E_status,temporal_orientation,order_1,order_2,context_order_1,context_order_2,context_only_deontic_question,context_only_epistemic_question
6,Training,T1,Museum entrance,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Lina is visiting a history museum tomorrow for...,One of the perks of Lina's green visitor badge...,According to the rules or permissions describe...,Based on the information described in the stor...
7,Training,T1,Museum entrance,D unspecified,E+ (weak / indirect evidence),past perfect / present progressive or stative,N-E,E-N,Lina visited a history museum this morning for...,"The museum has three entrances, and a classmat...",According to the rules or permissions describe...,Based on the information described in the stor...
8,Training,T2,Library rooms,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Priya is doing research at the library tomorro...,Priya's researcher card gives her permission t...,According to the rules or permissions describe...,Based on the information described in the stor...
9,Training,T2,Library rooms,D unspecified,E+ (weak / indirect evidence),past perfect / present progressive or stative,N-E,E-N,Priya is doing research at the library right n...,"The map room lights are on, and Priya is worki...",According to the rules or permissions describe...,Based on the information described in the stor...
10,Training,T3,Community center,D+,E+ (open / not ruled out),future eventive,N-D,D-N,Nora is going to the community center this aft...,Nora's membership allows her to use the swimmi...,According to the rules or permissions describe...,Based on the information described in the stor...

In [4]:
context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
    lambda x: x.replace("rules or permissions", "<b>rules or permissions</b>")
)
context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(
    lambda x: x.replace("information", "<b>information</b>")
)

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_21458/3176482508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_deontic_question"] = context_only["context_only_deontic_question"].apply(
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_21458/3176482508.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  context_only["context_only_epistemic_question"] = context_only["context_only_epistemic_question"].apply(

In [5]:
context_only = pd.concat([
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                }),
        context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "context_only_deontic_question",
            "context_only_epistemic_question"]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                })
    ])

print(context_only["D_status"].value_counts())
print(context_only["E_status"].value_counts())

context_only["D_status"] = context_only["D_status"].map({"D+": 1, "D unspecified": 0, "D-": -1})
context_only["E_status"] = context_only["E_status"].map({"E+ (weak / indirect evidence)": 1, "E+":1, "E+ (open / not ruled out)": 0, "E-": -1})


print(context_only["D_status"].value_counts())
print(context_only["E_status"].value_counts())

co_d = context_only[[
            "phase",
            "item_id",
            "domain",
            "D_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_deontic_question",
            ]].rename(columns={
                "D_status":"modal_possibility",
                "context_only_deontic_question":"context_only_question"
                })
co_d["judgement_flavour"] = "Deontic"
co_d["context_only_option_3"] = "The story does not say"

co_e = context_only[[
            "phase",
            "item_id",
            "domain",
            "E_status",
            "temporal_orientation",
            "order",
            "context_order",
            "context_only_epistemic_question",
            ]].rename(columns={
                "E_status":"modal_possibility",
                "context_only_epistemic_question":"context_only_question"
                })
co_e["judgement_flavour"] = "Epistemic"
co_e["context_only_option_3"] = ""


context_only = pd.concat([co_d, co_e]).sort_values(by=["item_id", "judgement_flavour", "modal_possibility", "order"]).reset_index(drop=True)

context_only.head(10)

D_status
D+               48
D unspecified    24
D-               24
Name: count, dtype: int64
E_status
E+ (open / not ruled out)        24
E+ (weak / indirect evidence)    24
E+                               24
E-                               24
Name: count, dtype: int64
D_status
 1    48
 0    24
-1    24
Name: count, dtype: int64
E_status
 1    48
 0    24
-1    24
Name: count, dtype: int64

,phase,item_id,domain,modal_possibility,temporal_orientation,order,context_order,context_only_question,judgement_flavour,context_only_option_3
0,Critical Test,C1,Zoo animal-care room,-1,past perfect,N-D-E,Aisha is photographing exhibits at the zoo. Th...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
1,Critical Test,C1,Zoo animal-care room,-1,past perfect,N-E-D,Aisha is photographing exhibits at the zoo. He...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
2,Critical Test,C1,Zoo animal-care room,1,future eventive,N-D-E,Aisha is volunteering at the zoo tomorrow. Her...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
3,Critical Test,C1,Zoo animal-care room,1,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
4,Critical Test,C1,Zoo animal-care room,-1,future eventive,N-D-E,Aisha is volunteering at the zoo tomorrow. Her...,Based on the <b>information</b> described in t...,Epistemic,
5,Critical Test,C1,Zoo animal-care room,-1,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,Based on the <b>information</b> described in t...,Epistemic,
6,Critical Test,C1,Zoo animal-care room,1,past perfect,N-D-E,Aisha is photographing exhibits at the zoo. Th...,Based on the <b>information</b> described in t...,Epistemic,
7,Critical Test,C1,Zoo animal-care room,1,past perfect,N-E-D,Aisha is photographing exhibits at the zoo. He...,Based on the <b>information</b> described in t...,Epistemic,
8,Critical Test,C2,University observatory,-1,present progressive,N-D-E,Theo is at the university observatory tonight....,According to the <b>rules or permissions</b> d...,Deontic,The story does not say
9,Critical Test,C2,University observatory,-1,present progressive,N-E-D,Theo is at the university observatory tonight....,According to the <b>rules or permissions</b> d...,Deontic,The story does not say

In [6]:
context_only.groupby(["phase", "judgement_flavour"])["modal_possibility"].value_counts()

phase          judgement_flavour  modal_possibility
Critical Test  Deontic            -1                   16
                                   1                   16
               Epistemic          -1                   16
                                   1                   16
Filler         Deontic            -1                    8
                                   1                    8
               Epistemic          -1                    8
                                   1                    8
Training       Deontic             0                   24
                                   1                   24
               Epistemic           0                   24
                                   1                   24
Name: count, dtype: int64

In [7]:
context_only["group"] = (context_only.index + context_only.index // 8) % 8 + 1
context_only["group"].tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 3,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 7,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 1,
 2,
 3,
 4,
 5,
 6,
 7]

In [8]:
print(context_only.shape)

context_only.to_csv("context_only_stimulus.csv")

(192, 11)

### whole-scenario norming

In [9]:
# need to norm both positive and negative responses. 

positive_df = pd.read_csv("../modal_experiment_v1_positive_flavour_stimulus_candidates.csv")
# The distributed CSV includes GENERAL NOTE rows without an item_id.
positive_df = positive_df.loc[positive_df["item_id"].notna()].copy()

positive_df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
6,6,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation
7,7,Training,T1,Museum entrance,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation
8,8,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation
9,9,Training,T2,Library rooms,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,Yes | No,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation
10,10,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation

In [10]:
negative_df = pd.read_csv("../modal_experiment_v1_negative_flavour_stimulus_candidates.csv")
# The distributed CSV includes GENERAL NOTE rows without an item_id.
negative_df = negative_df.loc[negative_df["item_id"].notna()].copy()

negative_df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,0,Critical Test,C1,Zoo animal-care room,Epistemic→Root (negated),D-,E+,explicit institutional restriction,open because relevant evidence is incomplete; ...,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
1,1,Critical Test,C1,Zoo animal-care room,Root→Epistemic (negated),D+,E-,explicit credential-based permission,categorically ruled out by an explicit future ...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
2,2,Critical Test,C2,University observatory,Epistemic→Root (negated),D-,E+,explicit training-based restriction,open because Theo's current location is unknown,present progressive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
3,3,Critical Test,C2,University observatory,Root→Epistemic (negated),D+,E-,explicit certification-based permission,categorically ruled out by an explicit future ...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
4,4,Critical Test,C3,Student film studio,Epistemic→Root (negated),D-,E+,explicit role-based restriction,open because the production record is incomplete,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN

In [11]:
positive_df["response_polarity"] = "positive"
negative_df["response_polarity"] = "negative"

df = pd.concat([positive_df, negative_df])
df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,response_polarity
6,6,Training,T1,Museum entrance,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation,positive
7,7,Training,T1,Museum entrance,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Declarative,Expected non-deontic interpretation,Expected epistemic interpretation,positive
8,8,Training,T2,Library rooms,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Wh-question,Expected root/deontic interpretation,Expected non-epistemic interpretation,positive
9,9,Training,T2,Library rooms,NaN,D unspecified,E+ (weak / indirect evidence),no relevant permission rule stated,weak or indirect evidence supports the target ...,past perfect / present progressive or stative,...,1–7 scale between the deontic and epistemic re...,D should be 'The story does not say',E+,NaN,Positive-only training candidate. Context-only...,Epistemic,Wh-question,Expected non-deontic interpretation,Expected epistemic interpretation,positive
10,10,Training,T3,Community center,NaN,D+,E+ (open / not ruled out),explicit permission/eligibility information wi...,no explicit epistemic evidence; the target eve...,future eventive,...,1–7 scale between the deontic and epistemic re...,D+,E+ (open / not ruled out),NaN,Positive-only training candidate. Context-only...,Root/deontic,Declarative,Expected root/deontic interpretation,Expected non-epistemic interpretation,positive

In [12]:
cols = [
    "phase",
    "item_id",
    "domain",
    "response_polarity",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "whole_scenario_may_target", "whole_scenario_possible_target",
    "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
    "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
    "syntax"
]

whole_scenario = df[cols].copy()

whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(
    lambda x: "What is the speaker talking about?" if x[-1] == "." \
        else "What is the speaker asking about?"
)

def get_name(target):
    s = target.split(" ")[1:]
    for w in s:
        if not str.islower(w):
            print(w)
            return w
    return " "

def fix_name(may_target, possible_target):
    may = may_target.split(" ")
    name = get_name(possible_target)
    may = [w if w != name.lower() else name for w in may]
    return " ".join(may)
    

# make sure the name is capitalized correctly
whole_scenario["whole_scenario_may_target"] = whole_scenario.apply(
    lambda x: fix_name(x["whole_scenario_may_target"], x["whole_scenario_possible_target"]),
    axis=1
)

whole_scenario.head()

# Preserve each actual context and its order label; code the two order versions.
context_versions = []
for context_code, suffix in enumerate([1, 2]):
    version = whole_scenario.drop(columns=[
        f"order_{3 - suffix}", f"context_order_{3 - suffix}"
    ]).rename(columns={
        f"order_{suffix}": "order",
        f"context_order_{suffix}": "context_order",
    }).copy()
    version["context_order_code"] = context_code
    context_versions.append(version)

whole_scenario = pd.concat(context_versions, ignore_index=True)
whole_scenario.head()

# Keep both target types in ONE response column, with a label for selection.
# Construct both types here so grouping never depends on a separate cell.
target_columns = {
    "whole_scenario_may_target": "may",
    "whole_scenario_possible_target": "possible",
}
response_versions = []
for target_column, response_type in target_columns.items():
    version = whole_scenario.drop(
        columns=[column for column in target_columns if column != target_column]
    ).rename(columns={target_column: "whole_scenario_response"}).copy()
    version["response_type"] = response_type
    response_versions.append(version)

whole_scenario = pd.concat(response_versions, ignore_index=True)
whole_scenario["whole_scenario_response"] = (
    whole_scenario["whole_scenario_response"].str.split(" — ").str[0]
)
whole_scenario["whole_scenario_deontic_reading"] = "The rules or permissions"
whole_scenario["whole_scenario_epistemic_reading"] = "The available information"
assert whole_scenario["response_type"].isin(["may", "possible"]).all()
assert whole_scenario["response_polarity"].isin(["positive", "negative"]).all()
print(whole_scenario.shape)
whole_scenario.head()

Lina
Lina
Priya
Priya
Nora
Nora
Kai
Kai
Omar
Omar
Maya
Maya
Eli
Eli
Sofia
Sofia
Mateo
Mateo
Ben
Ben
Nina
Nina
Daniel
Daniel
Aisha
Aisha
Theo
Theo
Grace
Grace
Jordan
Jordan
Chloe
Chloe
Marcus
Marcus
Elena
Elena
Ravi
Ravi
Tessa
Amir
Zoe
Henry
June
Samuel
Leah
Colin
Aisha
Aisha
Theo
Theo
Grace
Grace
Jordan
Jordan
Chloe
Chloe
Marcus
Marcus
Elena
Elena
Ravi
Ravi
Tessa
Amir
Zoe
Henry
June
Samuel
Leah
Colin
(288, 16)

,phase,item_id,domain,response_polarity,temporal_orientation,order,context_order,whole_scenario_response,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,whole_scenario_question,context_order_code,response_type
0,Training,T1,Museum entrance,positive,future eventive,N-D,Lina is visiting a history museum tomorrow for...,"Oh, so Lina may use the side entrance tomorrow.",The rules or permissions,The available information,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,What is the speaker talking about?,0,may
1,Training,T1,Museum entrance,positive,past perfect / present progressive or stative,N-E,Lina visited a history museum this morning for...,"Oh, so Lina may have used the side entrance.",The rules or permissions,The available information,Expected non-deontic interpretation,Expected epistemic interpretation,Declarative,What is the speaker talking about?,0,may
2,Training,T2,Library rooms,positive,future eventive,N-D,Priya is doing research at the library tomorro...,"Oh, so which room may Priya work in tomorrow?",The rules or permissions,The available information,Expected root/deontic interpretation,Expected non-epistemic interpretation,Wh-question,What is the speaker asking about?,0,may
3,Training,T2,Library rooms,positive,past perfect / present progressive or stative,N-E,Priya is doing research at the library right n...,"Oh, so which room may Priya be working in now?",The rules or permissions,The available information,Expected non-deontic interpretation,Expected epistemic interpretation,Wh-question,What is the speaker asking about?,0,may
4,Training,T3,Community center,positive,future eventive,N-D,Nora is going to the community center this aft...,"Oh, so Nora may use the pool this afternoon.",The rules or permissions,The available information,Expected root/deontic interpretation,Expected non-epistemic interpretation,Declarative,What is the speaker talking about?,0,may

In [13]:
# 2 response types x 2 scale orders x 4 item lists x 2 polarity rotations = 32 groups.
# Response type and scale order are fixed within a group. Temporal/context
# combinations and response polarity vary across items, one version per item.
import re

required_columns = {"response_type", "response_polarity", "whole_scenario_response",
                    "context_order", "context_order_code", "temporal_orientation"}
missing_columns = required_columns - set(whole_scenario.columns)
assert not missing_columns, (
    f"Missing prepared columns: {sorted(missing_columns)}. "
    "Rerun the whole-scenario preparation cell above before grouping."
)

variants = whole_scenario.rename(columns={"context_order": "context"}).copy()
variants["context_order"] = variants["context_order_code"]
temporal_codes = {
    "future eventive": 0,
    "past perfect / present progressive or stative": 1,
    "past perfect": 1,
    "present progressive": 1,
    "present stative": 1,
}
variants["temporal_code"] = variants["temporal_orientation"].map(temporal_codes)
assert variants["temporal_code"].notna().all(), "Unrecognized temporal orientation"
variants["temporal_code"] = variants["temporal_code"].astype(int)

# Natural ordering gives C1, C2, ... C8, F1, ... F8, T1, ... T12.
def item_sort_key(item_id):
    return tuple(int(part) if part.isdigit() else part
                 for part in re.split(r"(\d+)", str(item_id)))

item_ids = sorted(variants["item_id"].unique(), key=item_sort_key)
item_rank = {item_id: rank for rank, item_id in enumerate(item_ids)}
variants["item_rank"] = variants["item_id"].map(item_rank)
polarity_values = ["positive", "negative"]

# Polarity now distinguishes actual stimulus versions.
variant_keys = [
    "item_id", "response_type", "temporal_code",
    "context_order", "response_polarity",
]
assert not variants.duplicated(variant_keys).any(), "Duplicate stimulus version"
assert set(variants["response_polarity"]) == set(polarity_values), (
    "Unexpected response_polarity labels"
)

available_temporal = (
    variants.groupby("item_id")["temporal_code"].agg(lambda x: set(x))
)
assert available_temporal.map(
    lambda values: values in ({0}, {1}, {0, 1})
).all(), "Unexpected temporal versions"

paired_items = [
    item for item in item_ids if available_temporal[item] == {0, 1}
]
paired_rank = {item: rank for rank, item in enumerate(paired_items)}

# Preserve the available temporal version of fixed-temporal fillers.
fixed_items = [
    item for item in item_ids if len(available_temporal[item]) == 1
]
fixed_context_rank = {}
for temporal_code in [0, 1]:
    items = [
        item for item in fixed_items
        if available_temporal[item] == {temporal_code}
    ]
    fixed_context_rank.update({
        item: rank for rank, item in enumerate(items)
    })

# Some items (in particular training) have positive versions only.
# Rotate polarity only for items offering both actual response versions.
available_polarities = variants.groupby("item_id")["response_polarity"].agg(set)
variable_polarity_items = [
    item for item in item_ids if available_polarities[item] == set(polarity_values)
]
# Every temporal/context/response-type version of an item must offer the
# same polarity options. Otherwise selecting polarity independently is invalid.
polarity_coverage = variants.groupby(
    ["item_id", "response_type", "temporal_code", "context_order"]
)["response_polarity"].nunique()
expected_coverage = polarity_coverage.index.get_level_values("item_id").map(
    available_polarities.map(len)
)
assert (polarity_coverage.to_numpy() == expected_coverage.to_numpy()).all(), (
    "An item has inconsistent polarity availability across stimulus versions"
)

expanded_groups = []
group_definitions = []

for response_code, response_type in enumerate(["may", "possible"]):
    for scale_code, scale_order in enumerate([
        "deontic-epistemic", "epistemic-deontic"
    ]):
        for list_rotation in range(4):
            assignments = []

            for item in item_ids:
                if item in paired_rank:
                    combination = (paired_rank[item] + list_rotation) % 4
                    temporal_code, context_order = divmod(combination, 2)
                else:
                    temporal_code = next(iter(available_temporal[item]))
                    context_order = (
                        fixed_context_rank[item] + list_rotation
                    ) % 2

                assignments.append({
                    "item_id": item,
                    "response_type": response_type,
                    "temporal_code": temporal_code,
                    "context_order": context_order,
                })

            assignments = pd.DataFrame(assignments)

            # Alternate polarity within each temporal/context combination.
            # For odd-sized combinations, alternate which polarity gets the
            # extra item, keeping the overall polarity totals balanced too.
            base_polarity = pd.Series(
                0, index=assignments.index, dtype="int64"
            )
            extra_polarity = 0

            eligible_assignments = assignments.loc[
                assignments["item_id"].isin(variable_polarity_items)
            ]
            for _, indices in eligible_assignments.groupby(
                ["temporal_code", "context_order"], sort=True
            ).groups.items():
                indices = list(indices)
                base_polarity.loc[indices] = [
                    (position + extra_polarity) % 2
                    for position in range(len(indices))
                ]
                if len(indices) % 2:
                    extra_polarity = 1 - extra_polarity

            for polarity_rotation in range(2):
                group = (
                    response_code * 16
                    + scale_code * 8
                    + list_rotation * 2
                    + polarity_rotation
                    + 1
                )

                polarity_assignments = assignments.copy()
                polarity_assignments["response_polarity"] = (
                    (base_polarity + polarity_rotation) % 2
                ).map(dict(enumerate(polarity_values)))

                # Preserve the sole available polarity of fixed-polarity items.
                fixed_mask = ~polarity_assignments["item_id"].isin(
                    variable_polarity_items
                )
                polarity_assignments.loc[fixed_mask, "response_polarity"] = (
                    polarity_assignments.loc[fixed_mask, "item_id"].map(
                        lambda item: next(iter(available_polarities[item]))
                    )
                )

                selected = polarity_assignments.merge(
                    variants,
                    on=variant_keys,
                    how="left",
                    validate="one_to_one",
                    indicator=True,
                )

                missing = selected.loc[
                    selected["_merge"].ne("both"), variant_keys
                ]
                assert missing.empty, (
                    "Missing actual stimulus versions:\n"
                    + missing.to_string(index=False)
                )
                selected = selected.drop(columns="_merge")

                selected["group"] = group
                selected["response_code"] = response_code
                selected["scale_code"] = scale_code
                selected["scale_order"] = scale_order
                selected["list_rotation"] = list_rotation
                selected["polarity_rotation"] = polarity_rotation

                # Use reading endpoints from the selected polarity-specific row.
                left = (
                    "whole_scenario_deontic_reading"
                    if scale_code == 0
                    else "whole_scenario_epistemic_reading"
                )
                right = (
                    "whole_scenario_epistemic_reading"
                    if scale_code == 0
                    else "whole_scenario_deontic_reading"
                )
                selected["left_interpretation"] = selected[left]
                selected["right_interpretation"] = selected[right]

                expanded_groups.append(selected)
                group_definitions.append({
                    "group": group,
                    "response_type": response_type,
                    "scale_order": scale_order,
                    "scale_code": scale_code,
                    "list_rotation": list_rotation,
                    "polarity_rotation": polarity_rotation,
                })

group_conditions = pd.DataFrame(group_definitions)

whole_scenario_combined = (
    pd.concat(expanded_groups, ignore_index=True)
    .sort_values(["group", "item_rank"], kind="mergesort")
    .drop(columns="item_rank")
    .reset_index(drop=True)
)

In [14]:
# Check one version per item/group and fixed between-participant factors.
assert set(whole_scenario_combined["group"]) == set(range(1, 33))
item_group_counts = whole_scenario_combined.groupby(
    ["item_id", "group"]
).size()
assert item_group_counts.eq(1).all(), "An item repeats within a group"
assert whole_scenario_combined.groupby(
    "item_id"
)["group"].nunique().eq(32).all()

for column in ["response_type", "scale_order"]:
    assert whole_scenario_combined.groupby(
        "group"
    )[column].nunique().eq(1).all()

# Each participant sees both polarities. Only items offering both polarities
# can be balanced; positive-only training items retain their actual version.
polarity_counts = (
    whole_scenario_combined.groupby(["group", "response_polarity"])
    .size()
    .unstack("response_polarity", fill_value=0)
    .reindex(columns=polarity_values, fill_value=0)
)
assert polarity_counts.gt(0).all().all(), "A group is missing a polarity"
eligible_rows = whole_scenario_combined.loc[
    whole_scenario_combined["item_id"].isin(variable_polarity_items)
]
eligible_polarity_counts = (
    eligible_rows.groupby(["group", "response_polarity"])
    .size()
    .unstack("response_polarity", fill_value=0)
    .reindex(index=range(1, 33), columns=polarity_values, fill_value=0)
)
assert (
    eligible_polarity_counts.max(axis=1)
    - eligible_polarity_counts.min(axis=1)
).le(1).all(), "Unbalanced polarity among items offering both versions"

# Preserve the original temporal/context balancing.
combination_counts = (
    whole_scenario_combined.groupby(
        ["group", "temporal_code", "context_order"]
    )
    .size()
    .unstack(["temporal_code", "context_order"], fill_value=0)
)
assert set(combination_counts.columns) == {
    (0, 0), (0, 1), (1, 0), (1, 1)
}
assert combination_counts.gt(0).all().all(), (
    "A group is missing a temporal/context combination"
)

for temporal_code in [0, 1]:
    counts = combination_counts[temporal_code]
    assert (
        counts.max(axis=1) - counts.min(axis=1)
    ).le(1).all(), "Unbalanced context orders"

# For eligible items, polarity is balanced within each temporal/context combination.
within_combination_polarity = (
    eligible_rows.groupby(
        ["group", "temporal_code", "context_order", "response_polarity"]
    )
    .size()
    .unstack("response_polarity", fill_value=0)
    .reindex(columns=polarity_values, fill_value=0)
)
assert (
    within_combination_polarity.max(axis=1)
    - within_combination_polarity.min(axis=1)
).le(1).all(), "Unbalanced polarity within a temporal/context combination"

# Across eight lists per response/scale pair, each paired item sees
# every available temporal × context × polarity combination. Both-polarity
# items appear once per combination; fixed-polarity items appear twice.
paired_counts = (
    whole_scenario_combined.loc[
        whole_scenario_combined["item_id"].isin(paired_items)
    ]
    .groupby([
        "item_id", "response_type", "scale_order",
        "temporal_code", "context_order", "response_polarity",
    ])
    .size()
)
assert len(paired_counts) == sum(
    16 * len(available_polarities[item]) for item in paired_items
)
paired_expected = paired_counts.index.get_level_values("item_id").map(
    lambda item: 2 // len(available_polarities[item])
)
assert (paired_counts.to_numpy() == paired_expected.to_numpy()).all()

# Fixed-temporal items see each available context × polarity combination
# twice when both polarities exist, or four times when polarity is fixed.
fixed_counts = (
    whole_scenario_combined.loc[
        whole_scenario_combined["item_id"].isin(fixed_items)
    ]
    .groupby([
        "item_id", "response_type", "scale_order",
        "context_order", "response_polarity",
    ])
    .size()
)
assert len(fixed_counts) == sum(
    8 * len(available_polarities[item]) for item in fixed_items
)
fixed_expected = fixed_counts.index.get_level_values("item_id").map(
    lambda item: 4 // len(available_polarities[item])
)
assert (fixed_counts.to_numpy() == fixed_expected.to_numpy()).all()

# The two polarity rotations preserve temporal/context assignments and
# choose opposite polarities for every item in each response/scale/list.
rotation_pairs = whole_scenario_combined.pivot(
    index=["item_id", "response_type", "scale_order", "list_rotation"],
    columns="polarity_rotation",
    values=["temporal_code", "context_order", "response_polarity"],
)
for column in ["temporal_code", "context_order"]:
    assert rotation_pairs[column][0].eq(rotation_pairs[column][1]).all()
eligible_pairs = rotation_pairs.index.get_level_values("item_id").isin(
    variable_polarity_items
)
assert rotation_pairs.loc[eligible_pairs, "response_polarity"][0].ne(
    rotation_pairs.loc[eligible_pairs, "response_polarity"][1]
).all(), "Eligible items must have complementary polarities"
assert rotation_pairs.loc[~eligible_pairs, "response_polarity"][0].eq(
    rotation_pairs.loc[~eligible_pairs, "response_polarity"][1]
).all(), "Fixed-polarity items must retain their available version"

whole_scenario_combined.to_csv("whole_scenario_stimulus.csv", index=False)
print(
    "Verified 32 groups, one version per item/group, "
    "and balanced temporal/context/polarity assignments."
)
display(combination_counts)
print("All items (including fixed-polarity training):")
display(polarity_counts)
print("Items offering both polarities:")
display(eligible_polarity_counts)

Verified 32 groups, one version per item/group, and balanced temporal/context/polarity assignments.

temporal_code  0     1
context_order  0  1  0  1
group
1              7  6  8  7
2              7  6  8  7
3              6  7  7  8
4              6  7  7  8
5              7  6  8  7
6              7  6  8  7
7              6  7  7  8
8              6  7  7  8
9              7  6  8  7
10             7  6  8  7
11             6  7  7  8
12             6  7  7  8
13             7  6  8  7
14             7  6  8  7
15             6  7  7  8
16             6  7  7  8
17             7  6  8  7
18             7  6  8  7
19             6  7  7  8
20             6  7  7  8
21             7  6  8  7
22             7  6  8  7
23             6  7  7  8
24             6  7  7  8
25             7  6  8  7
26             7  6  8  7
27             6  7  7  8
28             6  7  7  8
29             7  6  8  7
30             7  6  8  7
31             6  7  7  8
32             6  7  7  8

All items (including fixed-polarity training):

response_polarity  positive  negative
group
1                        20         8
2                        20         8
3                        20         8
4                        20         8
5                        20         8
6                        20         8
7                        20         8
8                        20         8
9                        20         8
10                       20         8
11                       20         8
12                       20         8
13                       20         8
14                       20         8
15                       20         8
16                       20         8
17                       20         8
18                       20         8
19                       20         8
20                       20         8
21                       20         8
22                       20         8
23                       20         8
24                       20         8
25                       20         8
26                       20         8
27                       20         8
28                       20         8
29                       20         8
30                       20         8
31                       20         8
32                       20         8

Items offering both polarities:

response_polarity  positive  negative
group
1                         8         8
2                         8         8
3                         8         8
4                         8         8
5                         8         8
6                         8         8
7                         8         8
8                         8         8
9                         8         8
10                        8         8
11                        8         8
12                        8         8
13                        8         8
14                        8         8
15                        8         8
16                        8         8
17                        8         8
18                        8         8
19                        8         8
20                        8         8
21                        8         8
22                        8         8
23                        8         8
24                        8         8
25                        8         8
26                        8         8
27                        8         8
28                        8         8
29                        8         8
30                        8         8
31                        8         8
32                        8         8

In [15]:
whole_scenario_combined[whole_scenario_combined["group"] == 2][[
    "item_id", "response_type", "scale_order", "temporal_code",
    "context_order", "response_polarity", "list_rotation", "polarity_rotation"
]]

,item_id,response_type,scale_order,temporal_code,context_order,response_polarity,list_rotation,polarity_rotation
28,C1,may,deontic-epistemic,0,0,negative,0,1
29,C2,may,deontic-epistemic,0,1,negative,0,1
30,C3,may,deontic-epistemic,1,0,positive,0,1
31,C4,may,deontic-epistemic,1,1,negative,0,1
32,C5,may,deontic-epistemic,0,0,positive,0,1
33,C6,may,deontic-epistemic,0,1,positive,0,1
34,C7,may,deontic-epistemic,1,0,negative,0,1
35,C8,may,deontic-epistemic,1,1,positive,0,1
36,F1,may,deontic-epistemic,0,0,negative,0,1
37,F2,may,deontic-epistemic,1,0,positive,0,1
38,F3,may,deontic-epistemic,1,1,negative,0,1
39,F4,may,deontic-epistemic,0,1,negative,0,1
40,F5,may,deontic-epistemic,1,0,negative,0,1
41,F6,may,deontic-epistemic,1,1,positive,0,1
42,F7,may,deontic-epistemic,0,0,positive,0,1
43,F8,may,deontic-epistemic,1,0,positive,0,1
44,T1,may,deontic-epistemic,0,0,positive,0,1
45,T2,may,deontic-epistemic,0,1,positive,0,1
46,T3,may,deontic-epistemic,1,0,positive,0,1
47,T4,may,deontic-epistemic,1,1,positive,0,1
48,T5,may,deontic-epistemic,0,0,positive,0,1
49,T6,may,deontic-epistemic,0,1,positive,0,1
50,T7,may,deontic-epistemic,1,0,positive,0,1
51,T8,may,deontic-epistemic,1,1,positive,0,1
52,T9,may,deontic-epistemic,0,0,positive,0,1
53,T10,may,deontic-epistemic,0,1,positive,0,1
54,T11,may,deontic-epistemic,1,0,positive,0,1
55,T12,may,deontic-epistemic,1,1,positive,0,1

In [16]:
whole_scenario_combined.groupby("item_id")["group"].value_counts()

item_id  group
C1       1        1
         2        1
         3        1
         4        1
         5        1
                 ..
T9       28       1
         29       1
         30       1
         31       1
         32       1
Name: count, Length: 896, dtype: int64

In [17]:
whole_scenario_combined.head()

,item_id,response_type,temporal_code,context_order,response_polarity,phase,domain,temporal_orientation,order,context,...,whole_scenario_question,context_order_code,group,response_code,scale_code,scale_order,list_rotation,polarity_rotation,left_interpretation,right_interpretation
0,C1,may,0,0,positive,Critical Test,Zoo animal-care room,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,...,What is the speaker talking about?,0,1,0,0,deontic-epistemic,0,0,The rules or permissions,The available information
1,C2,may,0,1,positive,Critical Test,University observatory,future eventive,N-D-E,Theo is helping at the observatory tomorrow ni...,...,What is the speaker talking about?,1,1,0,0,deontic-epistemic,0,0,The rules or permissions,The available information
2,C3,may,1,0,negative,Critical Test,Student film studio,past perfect,N-E-D,Grace is working on a documentary at a student...,...,What is the speaker talking about?,0,1,0,0,deontic-epistemic,0,0,The rules or permissions,The available information
3,C4,may,1,1,positive,Critical Test,Hotel rooftop lounge,present stative,N-D-E,Jordan is attending a conference at a hotel to...,...,What is the speaker talking about?,1,1,0,0,deontic-epistemic,0,0,The rules or permissions,The available information
4,C5,may,0,0,negative,Critical Test,Aquatic center diving area,future eventive,N-E-D,Chloe is returning for swim practice tomorrow....,...,What is the speaker talking about?,0,1,0,0,deontic-epistemic,0,0,The rules or permissions,The available information

In [18]:
# Practice trials use the same scale order as their experimental group.
whole_scenario_practice = pd.read_csv("norming_practice_trials_whole_scenario.csv")
practice_groups = []
for condition in group_conditions.itertuples(index=False):
    p = whole_scenario_practice.copy()
    p["group"] = condition.group
    p["scale_order"] = condition.scale_order
    p["response_type"] = condition.response_type
    p["list_rotation"] = condition.list_rotation
    p["polarity_rotation"] = condition.polarity_rotation
    left = "whole_scenario_deontic_reading" if condition.scale_code == 0 else "whole_scenario_epistemic_reading"
    right = "whole_scenario_epistemic_reading" if condition.scale_code == 0 else "whole_scenario_deontic_reading"
    p["left_interpretation"] = p[left]
    p["right_interpretation"] = p[right]
    if condition.scale_code == 1:
        # Labels naming the interpretation stay unchanged. Reverse numeric
        # left/right answer codes only (CSV may load them as strings or numbers).
        p["expected_preference"] = p["expected_preference"].replace({
            "1": "2", "2": "1", 1: 2, 2: 1,
        })
    practice_groups.append(p)

whole_scenario_practice_grouped = pd.concat(practice_groups, ignore_index=True)
practice_scale = whole_scenario_practice_grouped.groupby("group")["scale_order"].first()
assert practice_scale.equals(group_conditions.set_index("group")["scale_order"])
whole_scenario_practice_grouped

,practice_id,context,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_preference,group,scale_order,response_type,list_rotation,polarity_rotation,left_interpretation,right_interpretation
0,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,What is the speaker talking about?,The rules or permissions,The available information,The rules or permissions,1,deontic-epistemic,may,0,0,The rules or permissions,The available information
1,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,What is the speaker talking about?,The rules or permissions,The available information,The available information,1,deontic-epistemic,may,0,0,The rules or permissions,The available information
2,P3,Rosa belongs to a sports club whose rules perm...,What time will Rosa play tennis today?,What is the speaker asking about?,The rules or permissions,The available information,The available information,1,deontic-epistemic,may,0,0,The rules or permissions,The available information
3,P4,A package was left either on the front porch o...,Was the mailman given authorization to enter t...,What is the speaker asking about?,The rules or permissions,The available information,The rules or permissions,1,deontic-epistemic,may,0,0,The rules or permissions,The available information
4,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,What is the speaker talking about?,The rules or permissions,The available information,The rules or permissions,2,deontic-epistemic,may,0,1,The rules or permissions,The available information
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,P4,A package was left either on the front porch o...,Was the mailman given authorization to enter t...,What is the speaker asking about?,The rules or permissions,The available information,The rules or permissions,31,epistemic-deontic,possible,3,0,The available information,The rules or permissions
124,P1,Ava is volunteering at a community garden. The...,The garden rules allow Ava to use the greenhouse.,What is the speaker talking about?,The rules or permissions,The available information,The rules or permissions,32,epistemic-deontic,possible,3,1,The available information,The rules or permissions
125,P2,Leo is visiting a community theater. Only thea...,Nobody knows whether Leo went backstage.,What is the speaker talking about?,The rules or permissions,The available information,The available information,32,epistemic-deontic,possible,3,1,The available information,The rules or permissions
126,P3,Rosa belongs to a sports club whose rules perm...,What time will Rosa play tennis today?,What is the speaker asking about?,The rules or permissions,The available information,The available information,32,epistemic-deontic,possible,3,1,The available information,The rules or permissions
127,P4,A package was left either on the front porch o...,Was the mailman given authorization to enter t...,What is the speaker asking about?,The rules or permissions,The available information,The rules or permissions,32,epistemic-deontic,possible,3,1,The available information,The rules or permissions

In [19]:
whole_scenario_practice_grouped.to_csv(
    "norming_practice_trials_whole_scenario_grouped.csv", index=False
)