In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../modal_experiment_v1_negative_flavour_stimulus_candidates.csv")
df = df.loc[df["item_id"].notna()].copy()
df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,0,Critical Test,C1,Zoo animal-care room,Epistemic→Root (negated),D-,E+,explicit institutional restriction,open because relevant evidence is incomplete; ...,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
1,1,Critical Test,C1,Zoo animal-care room,Root→Epistemic (negated),D+,E-,explicit credential-based permission,categorically ruled out by an explicit future ...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
2,2,Critical Test,C2,University observatory,Epistemic→Root (negated),D-,E+,explicit training-based restriction,open because Theo's current location is unknown,present progressive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
3,3,Critical Test,C2,University observatory,Root→Epistemic (negated),D+,E-,explicit certification-based permission,categorically ruled out by an explicit future ...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
4,4,Critical Test,C3,Student film studio,Epistemic→Root (negated),D-,E+,explicit role-based restriction,open because the production record is incomplete,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN

In [3]:
cols = [
    "phase",
    "item_id",
    "domain",
    "temporal_orientation",
    "order_1",
    "order_2",
    "context_order_1",
    "context_order_2",
    "whole_scenario_may_target", "whole_scenario_possible_target",
    "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
    "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
    "syntax"
]

whole_scenario = df[cols].copy()

whole_scenario["whole_scenario_question"] = whole_scenario["whole_scenario_may_target"].apply(
    lambda x: "What is the speaker talking about?" if x[-1] == "." \
        else "What is the speaker asking about?"
)

whole_scenario.head()

,phase,item_id,domain,temporal_orientation,order_1,order_2,context_order_1,context_order_2,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,whole_scenario_question
0,Critical Test,C1,Zoo animal-care room,past perfect,N-E-D,N-D-E,Aisha is photographing exhibits at the zoo. He...,Aisha is photographing exhibits at the zoo. Th...,It is not the case that Aisha may have gone in...,It is not possible for Aisha to have gone into...,About whether Aisha going into the animal-care...,About whether Aisha going into the animal-care...,NaN,NaN,NaN,What is the speaker talking about?
1,Critical Test,C1,Zoo animal-care room,future eventive,N-E-D,N-D-E,Aisha is volunteering at the zoo tomorrow. Ais...,Aisha is volunteering at the zoo tomorrow. Her...,It is not the case that Aisha may work in the ...,It is not possible for Aisha to work in the an...,About whether Aisha working in the animal-care...,About whether Aisha working in the animal-care...,NaN,NaN,NaN,What is the speaker talking about?
2,Critical Test,C2,University observatory,present progressive,N-E-D,N-D-E,Theo is at the university observatory tonight....,Theo is at the university observatory tonight....,It is not the case that Theo may be working in...,It is not possible for Theo to be working in t...,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,What is the speaker talking about?
3,Critical Test,C2,University observatory,future eventive,N-E-D,N-D-E,Theo is helping at the observatory tomorrow ni...,Theo is helping at the observatory tomorrow ni...,It is not the case that Theo may work in the t...,It is not possible for Theo to work in the tel...,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,What is the speaker talking about?
4,Critical Test,C3,Student film studio,past perfect,N-E-D,N-D-E,Grace is working on a documentary at a student...,Grace is working on a documentary at a student...,It is not the case that Grace may have gone in...,It is not possible for Grace to have gone into...,About whether Grace going into the sound-mixin...,About whether Grace going into the sound-mixin...,NaN,NaN,NaN,What is the speaker talking about?

In [4]:
# Preserve each actual context and its order label; code the two order versions.
context_versions = []
for context_code, suffix in enumerate([1, 2]):
    version = whole_scenario.drop(columns=[
        f"order_{3 - suffix}", f"context_order_{3 - suffix}"
    ]).rename(columns={
        f"order_{suffix}": "order",
        f"context_order_{suffix}": "context_order",
    }).copy()
    version["context_order_code"] = context_code
    context_versions.append(version)

whole_scenario = pd.concat(context_versions, ignore_index=True)
whole_scenario.head()

,phase,item_id,domain,temporal_orientation,order,context_order,whole_scenario_may_target,whole_scenario_possible_target,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,whole_scenario_question,context_order_code
0,Critical Test,C1,Zoo animal-care room,past perfect,N-E-D,Aisha is photographing exhibits at the zoo. He...,It is not the case that Aisha may have gone in...,It is not possible for Aisha to have gone into...,About whether Aisha going into the animal-care...,About whether Aisha going into the animal-care...,NaN,NaN,NaN,What is the speaker talking about?,0
1,Critical Test,C1,Zoo animal-care room,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,It is not the case that Aisha may work in the ...,It is not possible for Aisha to work in the an...,About whether Aisha working in the animal-care...,About whether Aisha working in the animal-care...,NaN,NaN,NaN,What is the speaker talking about?,0
2,Critical Test,C2,University observatory,present progressive,N-E-D,Theo is at the university observatory tonight....,It is not the case that Theo may be working in...,It is not possible for Theo to be working in t...,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,What is the speaker talking about?,0
3,Critical Test,C2,University observatory,future eventive,N-E-D,Theo is helping at the observatory tomorrow ni...,It is not the case that Theo may work in the t...,It is not possible for Theo to work in the tel...,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,What is the speaker talking about?,0
4,Critical Test,C3,Student film studio,past perfect,N-E-D,Grace is working on a documentary at a student...,It is not the case that Grace may have gone in...,It is not possible for Grace to have gone into...,About whether Grace going into the sound-mixin...,About whether Grace going into the sound-mixin...,NaN,NaN,NaN,What is the speaker talking about?,0

In [5]:
whole_scenario_may = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "context_order_code",
        "whole_scenario_may_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
        "syntax"
        ]].rename(columns={
            "whole_scenario_may_target":"whole_scenario_response",
        })
whole_scenario_may["response_type"] = "may"

whole_scenario_possible = whole_scenario[[
        "phase",
        "item_id",
        "domain",
        "temporal_orientation",
        "order",
        "context_order",
        "context_order_code",
        "whole_scenario_possible_target",
        "whole_scenario_question",
        "whole_scenario_deontic_reading", "whole_scenario_epistemic_reading",
        "expected_whole_scenario_deontic_interpretation", "expected_whole_scenario_epistemic_interpretation",
        "syntax"
        ]].rename(columns={
            "whole_scenario_possible_target":"whole_scenario_response",
        })
whole_scenario_possible["response_type"] = "possible"


whole_scenario_may.head()

,phase,item_id,domain,temporal_orientation,order,context_order,context_order_code,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,response_type
0,Critical Test,C1,Zoo animal-care room,past perfect,N-E-D,Aisha is photographing exhibits at the zoo. He...,0,It is not the case that Aisha may have gone in...,What is the speaker talking about?,About whether Aisha going into the animal-care...,About whether Aisha going into the animal-care...,NaN,NaN,NaN,may
1,Critical Test,C1,Zoo animal-care room,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,0,It is not the case that Aisha may work in the ...,What is the speaker talking about?,About whether Aisha working in the animal-care...,About whether Aisha working in the animal-care...,NaN,NaN,NaN,may
2,Critical Test,C2,University observatory,present progressive,N-E-D,Theo is at the university observatory tonight....,0,It is not the case that Theo may be working in...,What is the speaker talking about?,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,may
3,Critical Test,C2,University observatory,future eventive,N-E-D,Theo is helping at the observatory tomorrow ni...,0,It is not the case that Theo may work in the t...,What is the speaker talking about?,About whether Theo working in the telescope co...,About whether Theo working in the telescope co...,NaN,NaN,NaN,may
4,Critical Test,C3,Student film studio,past perfect,N-E-D,Grace is working on a documentary at a student...,0,It is not the case that Grace may have gone in...,What is the speaker talking about?,About whether Grace going into the sound-mixin...,About whether Grace going into the sound-mixin...,NaN,NaN,NaN,may

In [6]:
whole_scenario = pd.concat([whole_scenario_may, whole_scenario_possible]).reset_index(drop=True)

whole_scenario["whole_scenario_response"] = whole_scenario["whole_scenario_response"].apply(
    lambda x: x.split(" — ")[0])

whole_scenario["whole_scenario_deontic_reading"] = "The rules or permissions"
whole_scenario["whole_scenario_epistemic_reading"] = "The available information"

print(whole_scenario.shape)
whole_scenario.head()

(96, 15)

,phase,item_id,domain,temporal_orientation,order,context_order,context_order_code,whole_scenario_response,whole_scenario_question,whole_scenario_deontic_reading,whole_scenario_epistemic_reading,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,response_type
0,Critical Test,C1,Zoo animal-care room,past perfect,N-E-D,Aisha is photographing exhibits at the zoo. He...,0,It is not the case that Aisha may have gone in...,What is the speaker talking about?,The rules or permissions,The available information,NaN,NaN,NaN,may
1,Critical Test,C1,Zoo animal-care room,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,0,It is not the case that Aisha may work in the ...,What is the speaker talking about?,The rules or permissions,The available information,NaN,NaN,NaN,may
2,Critical Test,C2,University observatory,present progressive,N-E-D,Theo is at the university observatory tonight....,0,It is not the case that Theo may be working in...,What is the speaker talking about?,The rules or permissions,The available information,NaN,NaN,NaN,may
3,Critical Test,C2,University observatory,future eventive,N-E-D,Theo is helping at the observatory tomorrow ni...,0,It is not the case that Theo may work in the t...,What is the speaker talking about?,The rules or permissions,The available information,NaN,NaN,NaN,may
4,Critical Test,C3,Student film studio,past perfect,N-E-D,Grace is working on a documentary at a student...,0,It is not the case that Grace may have gone in...,What is the speaker talking about?,The rules or permissions,The available information,NaN,NaN,NaN,may

In [7]:
# 2 response types x 2 scale orders x 4 rotating item lists = 16 groups.
# Response and scale order are fixed within a group. The temporal/context
# combination rotates across items, with one actual version per item per group.
import re

variants = whole_scenario.rename(columns={"context_order": "context"}).copy()
variants["context_order"] = variants["context_order_code"]
temporal_codes = {
    "future eventive": 0,
    "past perfect / present progressive or stative": 1,
    "past perfect": 1,
    "present progressive": 1,
    "present stative": 1,
}
variants["temporal_code"] = variants["temporal_orientation"].map(temporal_codes)
assert variants["temporal_code"].notna().all(), "Unrecognized temporal orientation"
variants["temporal_code"] = variants["temporal_code"].astype(int)

# Natural ordering gives C1, C2, ... C8, F1, ... F8, T1, ... T12.
def item_sort_key(item_id):
    return tuple(int(part) if part.isdigit() else part
                 for part in re.split(r"(\d+)", str(item_id)))

item_ids = sorted(variants["item_id"].unique(), key=item_sort_key)
item_rank = {item_id: rank for rank, item_id in enumerate(item_ids)}
variants["item_rank"] = variants["item_id"].map(item_rank)
variant_keys = ["item_id", "response_type", "temporal_code", "context_order"]
assert not variants.duplicated(variant_keys).any(), "Duplicate stimulus version"
available_temporal = variants.groupby("item_id")["temporal_code"].agg(lambda x: set(x))
paired_items = [item for item in item_ids if available_temporal[item] == {0, 1}]
paired_rank = {item: rank for rank, item in enumerate(paired_items)}
# Some fillers have only one temporal version in the source CSV. Keep that
# version, and balance context order within each fixed temporal category.
fixed_items = [item for item in item_ids if len(available_temporal[item]) == 1]
fixed_context_rank = {}
for temporal_code in [0, 1]:
    items = [item for item in fixed_items if available_temporal[item] == {temporal_code}]
    fixed_context_rank.update({item: rank for rank, item in enumerate(items)})

expanded_groups = []
group_definitions = []
for response_code, response_type in enumerate(["may", "possible"]):
    for scale_code, scale_order in enumerate(["deontic-epistemic", "epistemic-deontic"]):
        for list_rotation in range(4):
            group = response_code * 8 + scale_code * 4 + list_rotation + 1
            assignments = []
            for item in item_ids:
                if item in paired_rank:
                    combination = (paired_rank[item] + list_rotation) % 4
                    temporal_code, context_order = divmod(combination, 2)
                else:
                    temporal_code = next(iter(available_temporal[item]))
                    context_order = (fixed_context_rank[item] + list_rotation) % 2
                assignments.append({
                    "item_id": item, "response_type": response_type,
                    "temporal_code": temporal_code, "context_order": context_order,
                })
            selected = pd.DataFrame(assignments).merge(
                variants, on=variant_keys, how="left", validate="one_to_one", indicator=True
            )
            assert selected["_merge"].eq("both").all(), "Missing actual stimulus version"
            selected = selected.drop(columns="_merge")
            selected["group"] = group
            selected["response_code"] = response_code
            selected["scale_code"] = scale_code
            selected["scale_order"] = scale_order
            selected["list_rotation"] = list_rotation
            # Use the item-specific reading endpoints from the selected source row.
            left = "whole_scenario_deontic_reading" if scale_code == 0 else "whole_scenario_epistemic_reading"
            right = "whole_scenario_epistemic_reading" if scale_code == 0 else "whole_scenario_deontic_reading"
            selected["left_interpretation"] = selected[left]
            selected["right_interpretation"] = selected[right]
            expanded_groups.append(selected)
            group_definitions.append({
                "group": group, "response_type": response_type,
                "scale_order": scale_order, "scale_code": scale_code,
                "list_rotation": list_rotation,
            })

group_conditions = pd.DataFrame(group_definitions)
whole_scenario_combined = pd.concat(expanded_groups, ignore_index=True).sort_values(
    ["group", "item_rank"], kind="mergesort"
).drop(columns="item_rank").reset_index(drop=True)

In [8]:
# Check assignment and counterbalancing before exporting.
assert set(whole_scenario_combined["group"]) == set(range(1, 17))
item_group_counts = whole_scenario_combined.groupby(["item_id", "group"]).size()
assert item_group_counts.eq(1).all(), "An item repeats within a group"
assert whole_scenario_combined.groupby("item_id")["group"].nunique().eq(16).all()
assert whole_scenario_combined.groupby("group")["response_type"].nunique().eq(1).all()
assert whole_scenario_combined.groupby("group")["scale_order"].nunique().eq(1).all()

combination_counts = whole_scenario_combined.groupby(
    ["group", "temporal_code", "context_order"]
).size().unstack(["temporal_code", "context_order"], fill_value=0)
assert set(combination_counts.columns) == {(0, 0), (0, 1), (1, 0), (1, 1)}
assert combination_counts.gt(0).all().all(), "A group is missing a combination"
# Fixed-temporal fillers can make the temporal totals unequal. Within each
# temporal category, context orders must still be as balanced as possible.
for temporal_code in [0, 1]:
    counts = combination_counts[temporal_code]
    assert (counts.max(axis=1) - counts.min(axis=1)).le(1).all(), "Unbalanced context orders"

# Each paired item sees all four combinations across the four lists of each
# response/scale pair. Fixed-temporal fillers see each context order twice.
paired_counts = whole_scenario_combined.loc[
    whole_scenario_combined["item_id"].isin(paired_items)
].groupby(["item_id", "response_type", "scale_order", "temporal_code", "context_order"]).size()
assert len(paired_counts) == len(paired_items) * 16 and paired_counts.eq(1).all()
fixed_counts = whole_scenario_combined.loc[
    whole_scenario_combined["item_id"].isin(fixed_items)
].groupby(["item_id", "response_type", "scale_order", "context_order"]).size()
assert len(fixed_counts) == len(fixed_items) * 8 and fixed_counts.eq(2).all()

whole_scenario_combined.to_csv("whole_scenario_stimulus_negative_flavour.csv", index=False)
print("Verified 16 groups, one version per item/group, and balanced combinations.")
combination_counts

Verified 16 groups, one version per item/group, and balanced combinations.

temporal_code  0     1
context_order  0  1  0  1
group
1              4  3  5  4
2              3  4  4  5
3              4  3  5  4
4              3  4  4  5
5              4  3  5  4
6              3  4  4  5
7              4  3  5  4
8              3  4  4  5
9              4  3  5  4
10             3  4  4  5
11             4  3  5  4
12             3  4  4  5
13             4  3  5  4
14             3  4  4  5
15             4  3  5  4
16             3  4  4  5

In [9]:
whole_scenario_combined[whole_scenario_combined["group"] == 1][[
    "item_id", "response_type", "scale_order", "temporal_code", "context_order"
]]

   item_id response_type        scale_order  temporal_code  context_order
0       C1           may  deontic-epistemic              0              0
1       C2           may  deontic-epistemic              0              1
2       C3           may  deontic-epistemic              1              0
3       C4           may  deontic-epistemic              1              1
4       C5           may  deontic-epistemic              0              0
5       C6           may  deontic-epistemic              0              1
6       C7           may  deontic-epistemic              1              0
7       C8           may  deontic-epistemic              1              1
8       F1           may  deontic-epistemic              0              0
9       F2           may  deontic-epistemic              1              0
10      F3           may  deontic-epistemic              1              1
11      F4           may  deontic-epistemic              0              1
12      F5           may  deontic-epistemic              1              0
13      F6           may  deontic-epistemic              1              1
14      F7           may  deontic-epistemic              0              0
15      F8           may  deontic-epistemic              1              0

In [10]:
whole_scenario_combined.groupby("item_id")["group"].value_counts()

item_id  group
C1       1        1
         2        1
         3        1
         4        1
         5        1
                 ..
F8       12       1
         13       1
         14       1
         15       1
         16       1
Name: count, Length: 256, dtype: int64

In [11]:
whole_scenario_combined.head()

,item_id,response_type,temporal_code,context_order,phase,domain,temporal_orientation,order,context,context_order_code,...,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,syntax,group,response_code,scale_code,scale_order,list_rotation,left_interpretation,right_interpretation
0,C1,may,0,0,Critical Test,Zoo animal-care room,future eventive,N-E-D,Aisha is volunteering at the zoo tomorrow. Ais...,0,...,NaN,NaN,NaN,1,0,0,deontic-epistemic,0,The rules or permissions,The available information
1,C2,may,0,1,Critical Test,University observatory,future eventive,N-D-E,Theo is helping at the observatory tomorrow ni...,1,...,NaN,NaN,NaN,1,0,0,deontic-epistemic,0,The rules or permissions,The available information
2,C3,may,1,0,Critical Test,Student film studio,past perfect,N-E-D,Grace is working on a documentary at a student...,0,...,NaN,NaN,NaN,1,0,0,deontic-epistemic,0,The rules or permissions,The available information
3,C4,may,1,1,Critical Test,Hotel rooftop lounge,present stative,N-D-E,Jordan is attending a conference at a hotel to...,1,...,NaN,NaN,NaN,1,0,0,deontic-epistemic,0,The rules or permissions,The available information
4,C5,may,0,0,Critical Test,Aquatic center diving area,future eventive,N-E-D,Chloe is returning for swim practice tomorrow....,0,...,NaN,NaN,NaN,1,0,0,deontic-epistemic,0,The rules or permissions,The available information